location: https://github.com/redhat-performance/coremark-wrapper/archive/refs/tags
exec_dir: "coremark-wrapper-2.4/coremark"
repo_file: "v2.4.tar.gz"
test_script_to_run: coremark_run
test_specific: "--iterations 5"
