location: https://github.com/redhat-performance/hammerdb-wrapper/archive/refs/tags
exec_dir: "hammerdb-wrapper-2.1/hammerdb"
repo_file: "v2.1.tar.gz"
os_supported: all
rhel_pkgs_9: lvm2,sysstat,tar,bc,nvme-cli,perf,git,unzip
rhel_pkgs: lvm2,sysstat,tar,bc,perf,git,unzip
ubuntu_pkgs: unzip,zip
amazon_pkgs: none
storage_required: "yes"
test_script_to_run: hammerdb
upload_extra: "/home/exports/hammerdb-tpcc.tar"
