location: https://github.com/redhat-performance/iozone-wrapper/archive/refs/tags
exec_dir: "iozone-wrapper-3.0/iozone"
repo_file: "v3.0.tar.gz"
storage_required: "yes"
test_script_to_run: iozone_run.sh
