location: https://github.com/redhat-performance/iozone-wrapper/archive/refs/tags
exec_dir: "iozone-wrapper-2.1/iozone"
repo_file: "v2.1.tar.gz"
storage_required: "yes"
test_script_to_run: iozone_run.sh
