location: https://github.com/redhat-performance/linpack-wrapper/archive/refs/tags
exec_dir: "linpack-wrapper-2.3/linpack"
repo_file: "v2.3.zip"
os_supported: all
rhel_pkgs: bc,numactl,perf,git,unzip
ubuntu_pkgs: unzip,zip,numactl
amazon_pkgs: bc,git,zip,unzip
test_script_to_run: linpack_run
test_specific: "--interleave all --iterations 1"
upload_extra: "/home/exports/l_onemklbench_p_2023.2.0_49340.tgz,/home/exports/xlinpack_xeon64-NEW"
