location: https://github.com/redhat-performance/linpack-wrapper/archive/refs/tags
exec_dir: "linpack-wrapper-3.2/linpack"
repo_file: "v3.2.tar.gz"
os_supported: all
rhel_pkgs: bc,numactl,perf,git,unzip
ubuntu_pkgs: unzip,zip,numactl
amazon_pkgs: bc,git,zip,unzip
test_script_to_run: linpack_run
test_specific: "--interleave all --iterations 1"
upload_extra: "/home/exports/xlinpack_xeon64-NEW"
