location: https://github.com/redhat-performance/passmark-wrapper/archive/refs/tags
exec_dir: "passmark-wrapper-2.5/passmark"
repo_file: "v2.5.tar.gz"
test_script_to_run: passmark_run
test_specific: "--iterations 5"
upload_extra: "/home/exports/pt_linux_x64.zip /home/exports/pt_linux_arm64.zip"
