location: https://github.com/redhat-performance/phoronix-wrapper/archive/refs/tags
exec_dir: "phoronix-wrapper-1.23/phoronix"
repo_file: "v1.23.zip"
rhel_pkgs: gcc,graphviz,python3,lksctp-tools-devel,php-cli,php-xml,php-json,bc,perf,git,unzip
ubuntu_pkgs: zip,gcc,graphviz,python3,lksctp-tools-devel,php-cli,php-xml,php-json,unzip,bc
amazon_pkgs: git build-essential,gcc,graphviz,python3,bc,git,zip,unzip,php-cli,php-xml
test_script_to_run: run_phoronix.sh
