location: https://github.com/redhat-performance/pyperf-wrapper/archive/refs/tags
exec_dir: "pyperf-wrapper-1.25/pyperf"
repo_file: "v1.25.zip"
rhel_pkgs: bc,numactl,perf,pip,python3-devel,git,unzip,wget
ubuntu_pkgs: unzip,zip,,python3-dev
amazon_pkgs: bc,git,zip,unzip
test_script_to_run: pyperf_run
