location: https://github.com/redhat-performance/specjbb-wrapper/archive/refs/tags
exec_dir: "specjbb-wrapper-2.1/specjbb"
repo_file: "v2.1.zip"
exec_dir: "specjbb-wrapper-2.1/specjbb"
rhel_pkgs: bc,numactl,perf,git,unzip
ubuntu_pkgs: libnuma-dev,unzip,zip
amazon_pkgs: numactl,bc,git,zip,unzip
java_required: "yes"
test_script_to_run: specjbb_run
upload_extra: "/home/exports/SPECjbb2005_kitv1.07.tar.gz"
