location: https://github.com/redhat-performance/speccpu2017-wrapper/archive/refs/tags
exec_dir: "speccpu2017-wrapper-2.2/speccpu2017"
repo_file: "v2.2.tar.gz"
storage_required: "yes"
test_script_to_run: run_speccpu
test_specific: "--test intrate,fprate"
upload_extra: "/home/exports/cpu2017-1.1.8.iso"
