location: https://github.com/redhat-performance/specjbb-wrapper/archive/refs/tags
repo_file: "v2.1.tar.gz"
exec_dir: "specjbb-wrapper-2.1/specjbb"
java_required: "yes"
test_script_to_run: specjbb_run
upload_extra: "/home/exports/SPECjbb2005_kitv1.07.tar.gz"
