on:
  push:
    branches:
      - main
  pull_request:

jobs:
  containerize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Quay
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_UNAME }}
          password: ${{ secrets.QUAY_PASSWD }}
        
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        if: github.event_name == 'push'
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: quay.io/zathras/zathras:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
          file: Containerfile

      - name: Build
        if: github.event_name != 'push'
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: quay.io/zathras/zathras:latest
          cache-from: type=gha
          platforms: linux/amd64,linux/arm64
          file: Containerfile
