#
# Variables for IBM VPC creation
#
ibm_vpc_profiles:
  - name: "bx2-2x8"
    description: "Balanced, 2 vCPUs, 8 GB RAM"
  - name: "bx2-4x16"
    description: "Balanced, 4 vCPUs, 16 GB RAM"
  - name: "bx2-8x32"
    description: "Balanced, 8 vCPUs, 32 GB RAM"
  - name: "bx2-16x64"
    description: "Balanced, 16 vCPUs, 64 GB RAM"
  - name: "bx2-32x128"
    description: "Balanced, 32 vCPUs, 128 GB RAM"
  - name: "bx2-48x192"
    description: "Balanced, 48 vCPUs, 192 GB RAM"
  - name: "cx2-2x4"
    description: "Compute, 2 vCPUs, 4 GB RAM"
  - name: "cx2-4x8"
    description: "Compute, 4 vCPUs, 8 GB RAM"
  - name: "cx2-8x16"
    description: "Compute, 8 vCPUs, 16 GB RAM"
  - name: "cx2-16x32"
    description: "Compute, 16 vCPUs, 32 GB RAM"
  - name: "cx2-32x64"
    description: "Compute, 32 vCPUs, 64 GB RAM"
  - name: "mx2-2x16"
    description: "Memory, 2 vCPUs, 16 GB RAM"
  - name: "mx2-4x32"
    description: "Memory, 4 vCPUs, 32 GB RAM"
  - name: "mx2-8x64"
    description: "Memory, 8 vCPUs, 64 GB RAM"
  - name: "mx2-16x128"
    description: "Memory, 16 vCPUs, 128 GB RAM"
  - name: "mx2-32x256"
    description: "Memory, 32 vCPUs, 256 GB RAM"

ibm_vpc_disk_profiles:
  - name: "general-purpose"
    description: "General purpose SSD"
  - name: "5iops-tier"
    description: "5 IOPS/GB tier"
  - name: "10iops-tier"
    description: "10 IOPS/GB tier"
  - name: "custom"
    description: "Custom IOPS"